CREATE TABLE check_ins
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    date         date,
    mood         INTEGER                                 NOT NULL,
    energy       INTEGER                                 NOT NULL,
    sleep        INTEGER                                 NOT NULL,
    focus        INTEGER                                 NOT NULL,
    hours_worked INTEGER                                 NOT NULL,
    score        INTEGER                                 NOT NULL,
    CONSTRAINT pk_check_ins PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_user VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    phone     VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE check_ins
    ADD CONSTRAINT FK_CHECK_INS_ON_USER FOREIGN KEY (user_id) REFERENCES usuario (id);