CREATE TABLE recommendation_model
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    check_in_id BIGINT,
    date        date,
    score       INTEGER,
    text        TEXT,
    CONSTRAINT pk_recommendationmodel PRIMARY KEY (id)
);

ALTER TABLE check_ins
    ALTER COLUMN date SET NOT NULL;

ALTER TABLE check_ins
    ALTER COLUMN user_id SET NOT NULL;