CREATE TABLE recommendation_model
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    date    date,
    score   INTEGER                                 NOT NULL,
    message VARCHAR(255),
    CONSTRAINT pk_recommendationmodel PRIMARY KEY (id)
);

ALTER TABLE recommendation_model
    ADD CONSTRAINT FK_RECOMMENDATIONMODEL_ON_USER FOREIGN KEY (user_id) REFERENCES usuario (id);